### ISSUE TITLE
Initial release todo checklist

### ISSUE THREAD

**Issue by Yuripetusko** [rmrk-team/rmrk-js#1]
- [x] Make sure rmrk-2d-renderer and nft-renderer packages output a plain css during the build process, with no dependency on tailwind/panda etc
- [x] Add tsc/build watch script for libraries and run them when example app `dev` script is run, to improve DX during development and for imported monorepo libraries would re-build on change to trigger hot-reload in nextjs dev server. If this proves to be slow (waiting for all packages to be rebuilt), then this alternative solution of modifying all paths in package.json from dist to src can be explored https://github.com/wevm/wagmi/blob/main/.scripts/preconstruct.ts
- [x] Write docs and usage examples
- [x] Add github actions CI scripts, including changesets integration
- [x] Cleanup code. Remove tailwind classes, improve hooks/functions naming consistency, remove dead code
- [x] Add a check for catalog type, and display an error if type is anything but image
- [x] Set up vitetest and add unit tests for both components/hooks and functions/utils using vitetests
- [x] Add other rmrk contracts to rmrkContracts config
- [x] Make sure there's a way to pass a custom chain and custom contracts for all tools to work with chains that are not specified in the hardcoded list
